{
  "uid" : "c2f14ffec3b133a5",
  "name" : "a1",
  "fullName" : "features/neonswap.feature:neonswap test:a1",
  "historyId" : "43c844bdc74364b1de0ceb550e33b61e",
  "time" : {
    "start" : 1636107166655,
    "stop" : 1636107167549,
    "duration" : 894
  },
  "description" : "",
  "status" : "failed",
  "statusMessage" : "processing response error (body=\"{\\\"jsonrpc\\\": \\\"2.0\\\", \\\"id\\\": 43, \\\"error\\\": {\\\"code\\\": -32000, \\\"message\\\": \\\"HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":43,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://proxy.teststand.neontest.xyz/solana\", code=SERVER_ERROR, version=web/5.5.0)",
  "statusTrace" : "Error: processing response error (body=\"{\\\"jsonrpc\\\": \\\"2.0\\\", \\\"id\\\": 43, \\\"error\\\": {\\\"code\\\": -32000, \\\"message\\\": \\\"HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":43,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://proxy.teststand.neontest.xyz/solana\", code=SERVER_ERROR, version=web/5.5.0)\n    at Logger.makeError (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at /home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/src.ts/index.ts:284:28\n    at step (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "time" : { },
    "status" : "broken",
    "steps" : [ {
      "name" : "Before: tests/step-definitions/hooks.ts:9",
      "time" : {
        "start" : 1636107166655,
        "stop" : 1636107166656,
        "duration" : 1
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "testStage" : {
    "description" : "",
    "status" : "failed",
    "statusMessage" : "processing response error (body=\"{\\\"jsonrpc\\\": \\\"2.0\\\", \\\"id\\\": 43, \\\"error\\\": {\\\"code\\\": -32000, \\\"message\\\": \\\"HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":43,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://proxy.teststand.neontest.xyz/solana\", code=SERVER_ERROR, version=web/5.5.0)",
    "statusTrace" : "Error: processing response error (body=\"{\\\"jsonrpc\\\": \\\"2.0\\\", \\\"id\\\": 43, \\\"error\\\": {\\\"code\\\": -32000, \\\"message\\\": \\\"HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":43,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://proxy.teststand.neontest.xyz/solana\", code=SERVER_ERROR, version=web/5.5.0)\n    at Logger.makeError (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at /home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/src.ts/index.ts:284:28\n    at step (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "steps" : [ {
      "name" : "Given there is connection to Neonswap",
      "time" : {
        "start" : 1636107166656,
        "stop" : 1636107167548,
        "duration" : 892
      },
      "status" : "failed",
      "statusMessage" : "processing response error (body=\"{\\\"jsonrpc\\\": \\\"2.0\\\", \\\"id\\\": 43, \\\"error\\\": {\\\"code\\\": -32000, \\\"message\\\": \\\"HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":43,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://proxy.teststand.neontest.xyz/solana\", code=SERVER_ERROR, version=web/5.5.0)",
      "statusTrace" : "Error: processing response error (body=\"{\\\"jsonrpc\\\": \\\"2.0\\\", \\\"id\\\": 43, \\\"error\\\": {\\\"code\\\": -32000, \\\"message\\\": \\\"HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\\\"}}\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_blockNumber\\\",\\\"params\\\":[],\\\"id\\\":43,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"https://proxy.teststand.neontest.xyz/solana\", code=SERVER_ERROR, version=web/5.5.0)\n    at Logger.makeError (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at /home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/src.ts/index.ts:284:28\n    at step (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/home/runner/work/neon-e2e/neon-e2e/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "And next attempts",
      "time" : {
        "start" : 1636107167548,
        "stop" : 1636107167549,
        "duration" : 1
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "thread",
    "value" : "3091"
  }, {
    "name" : "feature",
    "value" : "neonswap test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "c2f14ffec3b133a5.json",
  "parameterValues" : [ ]
}